#
# DCC Metadata Server - Configuration
#

###################################################################################################
# Development
###################################################################################################

# Spring
spring:
  profiles: development

# Mongo
spring.data.mongodb:
  uri: mongodb://localhost/dcc-metadata  
