---
#
# DCC Metadata Server - Configuration
#

###################################################################################################
# Common
###################################################################################################

# Postgres
postgres:
   user: dcc
   password: <fill in>
   database: fathmm
   server: hcn-117.res.oicr.on.ca
   url: jdbc:postgresql://${postgres.server}/${postgres.database}?user=${postgres.user}&password=${postgres.password}

---

###################################################################################################
# Production
###################################################################################################

# Spring
spring:
   profiles: production

---

###################################################################################################
# Development
###################################################################################################

# Spring
spring:
   profiles: development
   

