#
# DCC Metadata Server - Configuration
#

###################################################################################################
# Common
###################################################################################################

spring:
  profiles.active: production

# Server
server:
  port: 8443
  ssl:
    key-store: src/main/conf/keystore.p12
    key-store-type: PKCS12
    key-store-password: P@ssw0rd

# Management endpoints
management:
  context_path: /admin
  address: 127.0.0.1
  port: 8444

# Postgres
postgres:
  user: dcc
  password: <fill in>
  database: fathmm
  server: hcn-117.res.oicr.on.ca
  url: jdbc:postgresql://${postgres.server}/${postgres.database}?user=${postgres.user}&password=${postgres.password}

---

###################################################################################################
# Production
###################################################################################################

# Spring
spring:
  profiles: production
  profiles.include: secure,development

---

###################################################################################################
# Development
###################################################################################################

# Spring
spring:
  profiles: development
   
---

###################################################################################################
# Secure
###################################################################################################

# Spring
spring:
  profiles: secure
   
# OAuth authentication server
auth:
  server:
    url: https://auth.icgc.org/oauth/check_token
    clientId: resource
    clientsecret: pass
    
  # Connection retries in case of connection failure 
  connection:
  
    # Max number of retries
    maxRetries: 5
    
    # Initial timeout before the first retry. In milliseconds.
    initialBackoff: 15000
    
    # Multiplier that defines value of consequent timeouts before the next retry. 
    # E.g. TIMEOUT(n) = TIMEOUT(n-1) * MULTIPLIER
    multiplier: 2.0
