#
# DCC Metadata Client - Configuration
#

accessToken: 3e0e7028-98e3-4ed8-b145-9c5160111eb7
server:
  baseUrl: https://storagedev.cancercollaboratory.org:8443/
   
  # Connection retries in case of connection failure 
  connection:

    # Max number of retries
    maxRetries: 5
    
    # Initial timeout before the first retry. In milliseconds.
    initialBackoff: 15000
    
    # Multiplier that defines value of consequent timeouts before the next retry. 
    # E.g. TIMEOUT(n) = TIMEOUT(n-1) * MULTIPLIER
    multiplier: 2.0

spring.main.show_banner: false
