---
#
# DCC Metadata Server - Configuration
#

###################################################################################################
# Common
###################################################################################################

accessToken: xxx-token-xxx
server:
   baseUrl: http://localhost:8080

logging.level.org.springframework.web: TRACE

---

###################################################################################################
# Production
###################################################################################################

# Spring
spring:
   profiles: production

---

###################################################################################################
# Development
###################################################################################################

# Spring
spring:
   profiles: development
   

